#ifndef GAME_CONFIG_H
#define GAME_CONFIG_H

#define WINDOW_WIDTH 1400
#define WINDOW_HEIGHT 750
#define MAN_WIDTH 50
#define MAN_HEIGHT 40
#define GRAVITY 0.5f
#define JUMP_FORCE -10.0f
#define MAX_OBSTACLES 1
#define INITIAL_SPEED 5.0f
#define ANIMAL_SPEED 1.5f
#define BIRD_SPEED 3.0f
#define GROUND_HEIGHT 550
#define ANIMAL_SPAWN_DISTANCE 300.0f
#define BIRD_SPAWN_DISTANCE 600.0f
#define BIRD_WIDTH 30
#define BIRD_HEIGHT 20
#define ANIMAL_WIDTH 40
#define ANIMAL_HEIGHT 30
#define MAX_ENEMIES 1
#define ROCK_HEIGHT_MAX 40
#define ROCK_HEIGHT_MIN 20
#define MIN_SPAWN_DISTANCE 200.0f
#define BIRD_Y_POSITION (GROUND_HEIGHT - 25)
#define ANIMAL_Y_POSITION (GROUND_HEIGHT - ANIMAL_HEIGHT)
#define DAY_DURATION 10000
#define MOON_SIZE 30
#define STAR_COUNT 200
#define SCORE_HEIGHT 50
#define MAX_COINS 20
#define COIN_SIZE 15
#define COIN_VALUE 10

#endif